name: Save Check Results

on:
  check_run:
    types: [completed]

jobs:
  process-check:
    runs-on: ubuntu-latest
    if: |
      github.event.check_run.app.slug == 'codebeaver-staging' &&
      contains(fromJSON('["failure", "skipped", "success"]'), github.event.check_run.conclusion)

    steps:
      - name: Get date
        id: get_date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
      - id: "update_worksheet"
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: 11QvkZsqomQ65ns0XBse0xCl8fjUAWbwduYt6xIq4YC8
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "appendData",
                "args": {
                  "worksheetTitle": "staging-release-${{ steps.get_date.outputs.date }}",
                  "data": [[
                    "${{ github.repository }}",
                    "${{ github.event.check_run.pull_requests[0].number }}",
                    "${{ github.event.check_run.conclusion }}",
                    "${{ github.event.check_run.output.summary || '' }}"
                  ]],
                   "minCol": 2
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
