name: Save Check Results
description: Save the results of a check run to a spreadsheet and then checks if we tested all of the PRs. If  so, it triggers another workflow to report the results.

on:
  check_run:
    types: [completed]

jobs:
  process-check:
    runs-on: ubuntu-latest
    if: |
      github.event.check_run.app.slug == 'codebeaver-staging' &&
      contains(fromJSON('["failure", "skipped", "success"]'), github.event.check_run.conclusion)

    steps:
      - name: Get date
        id: get_date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
      - id: "update_worksheet"
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: 11QvkZsqomQ65ns0XBse0xCl8fjUAWbwduYt6xIq4YC8
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "appendData",
                "args": {
                  "worksheetTitle": "staging-release-${{ steps.get_date.outputs.date }}",
                  "data": [[
                    "${{ github.repository }}",
                    "${{ github.event.check_run.pull_requests[0].number }}",
                    "${{ github.event.check_run.conclusion }}",
                    "${{ github.event.check_run.output.summary || '' }}"
                  ]],
                   "minCol": 1
                }
              }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Grab lines in spreadsheet
        id: grab_lines
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: 11QvkZsqomQ65ns0XBse0xCl8fjUAWbwduYt6xIq4YC8
          commands: |
            [
              { "command": "getData", "args": { "range": "staging-release-${{ steps.get_date.outputs.date }}!A:A" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Get counter (A2 cell)
        id: get_counter
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: 11QvkZsqomQ65ns0XBse0xCl8fjUAWbwduYt6xIq4YC8
          commands: |
            [
              { "command": "getData", "args": { "range": "staging-release-${{ steps.get_date.outputs.date }}!B1" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: Adjust line count for headers
        id: adjust_line_count
        run: |
          # Parse the JSON result and safely get the length
          LINE_COUNT=$(echo ${{ steps.grab_lines.outputs.result }} | jq '.values | length')
          # Subtract header rows (adjust number if needed)
          ADJUSTED_COUNT=$((LINE_COUNT - 3))
          echo "line_count=${ADJUSTED_COUNT}" >> $GITHUB_ENV

          # Safely parse the counter value
          COUNTER=$(echo ${{ steps.get_counter.outputs.result }} | jq '.values[0][0]' -r)
          echo "counter=${COUNTER}" >> $GITHUB_ENV

      - name: Debug line count
        run: |
          echo "Line count: ${{ env.line_count }}"
          echo "Counter value: ${{ env.counter }}"

      - name: Trigger another workflow
        if: ${{ env.line_count >= env.counter && env.counter > 0 }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "report-all-test-prs"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
